# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none
FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: false
IGNORE_GITIGNORED_FILES: true
LINTER_RULES_PATH: .
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: false
#VALIDATE_ALL_CODEBASE: false   # For some reason, this fails in v6 of ML (?)

ENABLE:
  #- ACTION     # An unknown shell check error is causing failures here - re-enable later
  - COPYPASTE
  - EDITORCONFIG
  - ENV
  - JSON
  - MAKEFILE
  - MARKDOWN
  - REPOSITORY
  - SPELL
  - YAML

DISABLE_LINTERS:
  - JSON_PRETTIER
  - YAML_PRETTIER
